name: "Build systems to test configurations"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        nixPath:
          - nixpkgs=channel:nixos-unstable
          - nixpkgs=channel:nixos-24.11
        host:
          - ci-big
          - ci-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@v30
      with:
        nix_path: "${{ matrix.nixPath }}"
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Show nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - name: build NixOS system
      run: nix-shell -p nixos-rebuild --run "nixos-rebuild build --flake .#${{ matrix.host }} --show-trace"
